config/routes.rb
StampApp::Application.routes.draw do
  resources :categories

  resources :payment_notifications
  	get 'tags/:tag', to: 'stamps#index', as: :tag
  
  resources :stamps do
    #get :clone
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
    
  resources :charges
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root :to => 'stamps#index'
  
  devise_for :admins
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :stamps, through: :categorizations
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base	
	acts_as_taggable
	#acts_as_taggable_on :categories
	has_many :assets
	has_many :categorizations
  has_many :categories, through: :categorizations
	accepts_nested_attributes_for :assets, :allow_destroy => true
	self.per_page = 25

  
	has_attached_file :image, :styles => {  :large => "600x600>", :medium => "300x300>", :thumb => "128x128>" }, :default_url => "/images/:style/missing.png"
	has_attached_file :image2, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "128x128>" }, :default_url => "/images/:style/missing.png"
	has_attached_file :image3, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "128x128>" }, :default_url => "/images/:style/missing.png"
	has_attached_file :image4, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "128x128>" }, :default_url => "/images/:style/missing.png"
	has_attached_file :image5, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "128x128>" }, :default_url => "/images/:style/missing.png"

  def self.search(search)
    if Rails.env.development?
      if search
        #find(:all, :conditions => ["\"Title\" LIKE ?", "%#{search}%"] )
        where(["\"Title\" LIKE ?" , "%#{search}%"] )
      else
        scoped
      end
    else
      if search
        where("\"Title\" @@ :s or \"Description\" @@ :s" , s: search )
      else
        scoped
      end
    end
  end
  
	#validates_attachment_presence :image
	#validates_attachment_size :image, :less_than => 5.megabytes
	#validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :set_stamp, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:edit, :update, :destroy, :new, :create, :duplicate, :update_multiple, :edit_multiple, :clone]
  # autocomplete :tag, :name
  
  # GET /stamps
  # GET /stamps.json
  def index
    if params[:tag]
      @stamps = Stamp.tagged_with(params[:tag]).paginate(:page => params[:page])
    else
      @stamps = Stamp.search(params[:search]).paginate(:page => params[:page])
    end
  end

  # GET /stamps/1
  # GET /stamps/1.json
  def show
  end

  # GET /stamps/new
  def new
    @stamp = Stamp.new
    6.times { @stamp.assets.build}
  end


#  def clone
#    @stamp = Stamp.find(params[:id]) # find original object
#    @stamp = Stamp.new(@stamp.attributes) # initialize duplicate (not saved)
#    render :new # render same view as "new", but with @stamp attributes already filled in
#  end

  # GET /stamps/1/edit
  def edit
    @stamp = Stamp.find(params[:id])
    6.times { @stamp.assets.build}
  end

  def edit_multiple
    @stamps = Stamp.find(params[:stamp_ids])
  end
  
  def update_multiple
    @stamps = Stamp.find(params[:stamp_ids])
    @stamps.each do |stamp|
      stamp.update(stamp_params)
    end
    flash[:notice] = "Updated stamps!"
    redirect_to stamps_path
  end

  # POST /stamps
  # POST /stamps.json
  def create
    @stamp = Stamp.new(stamp_params)

    respond_to do |format|
      if @stamp.save
        format.html { redirect_to @stamp, notice: 'Stamp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stamp }
      else
        format.html { render action: 'new' }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /stamps/1
  # PATCH/PUT /stamps/1.json
  def update
    respond_to do |format|
      if @stamp.update(stamp_params)
        format.html { redirect_to @stamp, notice: 'Stamp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stamps/1
  # DELETE /stamps/1.json
  def destroy
    @stamp.destroy
    respond_to do |format|
      format.html { redirect_to stamps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stamp
      @stamp = Stamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stamp_params
      params.require(:stamp).permit(:Title, :Description, :Price, :notes, :image, :image2, :image3, :image4, :image5, :asset, :tag_list, :categories, :stamp, :category_ids => [])
    end
end

app/helpers/stamps_helper.rb
module StampsHelper
  def add_asset_link(name) 
    link_to_function name do |stamp| 
      stamp.insert_html :bottom, :assets, :partial => 'asset', :object => Asset.new 
    end 
  end
  
  ##def duplicate
#    @existing_stamp = Stamp.find(params[:id])
#    #create new object with attributes of existing record 
#    Stamp.new
#    @stamp = Stamp.new(@existing_stamp.attributes)  
#  end
  
end

app/views/stamps/_asset.html.erb
<div class="asset"> 
    <% new_or_existing = asset.new_record? ? 'new' : 'existing' %>
    <% prefix = "post[#{new_or_existing}_asset_attributes][]" %>

    <% fields_for prefix, asset do |asset_form| -%> 
        <p> 
          Asset: <%= asset_form.file_field :photo %> 
          <%= link_to_function "remove", "$(this).up('.asset').remove()" %> 
        </p> 
  <% end -%> 
</div>

app/views/stamps/_form.html.erb
<%= simple_form_for(@stamp, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Title %>
    <%= f.input :Description %>
    <%= f.input :Price %>
  </div>
  
  <!--
  <%= f.association :categories,  as: :check_boxes %>	
  -->
	
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list %>
  </div>

	<p>Image 1 (Main display picture)<br>
		<%=f.file_field :image %>
	</p>

  <p>Additional Images<br>
    <%=f.file_field :image2 %>
    <%=f.file_field :image3 %>
    <%=f.file_field :image4 %>
    <%=f.file_field :image5 %>
  </p>

  <div>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stamps/edit.html.erb
<h1>Editing stamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @stamp %> |
<%= link_to 'Back', stamps_path %>

app/views/stamps/edit_multiple.html.erb
<%= form_for :stamp, :url => update_multiple_stamps_path, :html => { :method => :put } do |f| %>
  <ul>
    <% for stamp in @stamps %>
      <li>
        <%= hidden_field_tag "stamp_ids[]", stamp.id %>
        <%=h stamp.Title %>
      </li>
    <% end %>
  </ul>
  <p>
    <%= f.label :Price %><br />
    <%= f.text_field :Price %>
  </p>
  
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/stamps/index.html.erb
<h3>Search All Stamps</h3>

<div id="search">
<%= form_tag stamps_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
</div>

<hr>
<%= form_tag edit_multiple_stamps_path do %>
<table>
  <thead>
    <tr>
      <% if admin_signed_in? %>
      	<%= raw '<th></th>' %>
      <% end %>
      <th>Title</th>
      <th>Picture</th>
      <th>Price</th>
      <th>Categories</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <div class="apple_pagination"><%= will_paginate @stamps %></div>
  <tbody>
    <% @stamps.reverse_each do |stamp| %>
      <tr>
      	<% if admin_signed_in? %>
      		<td><%= check_box_tag "stamp_ids[]", stamp.id %></td>
      	<% end %>
        <td><strong><h4><%= link_to stamp.Title, stamp %></h4></strong></td>
        <td><%= image_tag stamp.image.url :thumb %></td>
        <td><h4><%= number_to_currency(stamp.Price) %></h4></td>
        <td><h5><%= raw stamp.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %></h5></td>
        <td><%= link_to 'Show', stamp if admin_signed_in? %></td>
        <td><%= link_to 'Edit', edit_stamp_path(stamp) if admin_signed_in?  %></td>
        <td><%= link_to 'Destroy', stamp, method: :delete, data: { confirm: 'Are you sure?' } if admin_signed_in?   %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="apple_pagination"><%= will_paginate @stamps %></div>
<%= submit_tag "Edit Checked" if admin_signed_in? %>
<% end %>
<br>

<%= link_to 'New Stamp', new_stamp_path if admin_signed_in? %>

<br><br>
<hr>

app/views/stamps/new.html.erb
<h1>New stamp</h1>

<%= render 'form' %>

<%= link_to 'Back', stamps_path %>

app/views/stamps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stamp_path(@stamp) if admin_signed_in? %> 
<%= link_to 'Back', stamps_path if admin_signed_in? %>
<%= link_to 'New Stamp', new_stamp_path if admin_signed_in? %>

<p>
  <h2><u><%= @stamp.Title %></u></h2>
</p>

<br/>
<%= image_tag @stamp.image.url %>
<%= image_tag @stamp.image2.url if @stamp.image2.url !=  "/images/original/missing.png"  %>
<%= image_tag @stamp.image3.url if @stamp.image3.url !=  "/images/original/missing.png"  %>
<%= image_tag @stamp.image4.url if @stamp.image4.url !=  "/images/original/missing.png"  %>
<%= image_tag @stamp.image5.url if @stamp.image4.url !=  "/images/original/missing.png"  %>
<br/><br/>

<p>
  <strong>Description:</strong><br/>
  <%= @stamp.Description %>
</p>

<p>
  <strong>Price:</strong><br/>
  <%= number_to_currency(@stamp.Price) %>
</p>

<p>
  <strong>Terms of Sale:</strong><br/>
  Before making a purchase, please read the <%= link_to 'Terms of Sale', 'https://sites.google.com/site/banknotestamps/home/Terms-of-Sale' %>.
</p>

<p>
  <strong>Categories:</strong><br/>
  <%= raw @stamp.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
</p>

<!--
<% @stamp.categories.each do |category| %>
    <li><%= category.name %></li>
<% end %>
-->

<p>
  <% if admin_signed_in? %>
    <strong>Notes:</strong><br/>
    <%= @stamp.notes if admin_signed_in? %>
  <% end %>
</p>

<br>

<!-- delete the 'sandbox' from this url in production-->
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">

<!-- Identify your business so that you can collect the payments. -->
<input type="hidden" name="business" value="frank.garmon.05@cnu.edu">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="item_name" value="<%= @stamp.Title %>">
<input type="hidden" name="amount" value="<%= @stamp.Price %>">
<input type="hidden" name="item_number" value="<%= @stamp.id %>">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="shopping_url" value="http://www.banknotestamps.com/">
<input type="hidden" name="notify_url" value="http://www.banknotestamps.com/">
<input type="hidden" name="return" value="http://store.banknotestamps.com/pages/thanks">
<input type="image" name="submit" border="0"
src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif"
alt="PayPal - The safer, easier way to pay online">
<img alt="" border="0" width="1" height="1"
src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >
</form>

<br>
<form target="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post" >
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="frank.garmon.05@cnu.edu">
<input type="hidden" name="lc" value="US">
<input type="hidden" name="item_name" value="<%= @stamp.Title %>">
<input type="hidden" name="amount" value="<%= @stamp.Price %>">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="button_subtype" value="products">
<input type="hidden" name="no_note" value="0">
<input type="hidden" name="add" value="1">
<input type="hidden" name="bn" value="PP-ShopCartBF:btn_cart_LG.gif:NonHostedGuest">
<input type="hidden" name="return" value="http://store.banknotestamps.com/pages/thanks">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_cart_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

<br> 

<%= link_to 'Edit', edit_stamp_path(@stamp) if admin_signed_in? %> |
<%= link_to 'Back', stamps_path %> |
<%= link_to 'New Stamp', new_stamp_path if admin_signed_in? %>