config/routes.rb
StampApp::Application.routes.draw do
  resources :categories

  resources :payment_notifications
  	get 'tags/:tag', to: 'stamps#index', as: :tag
  
  resources :stamps do
    #get :clone
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
    
  resources :charges
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root :to => 'stamps#index'
  
  devise_for :admins
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
	belongs_to :stamp
	serialize :params
	after_create :mark_stamp_as_purchased

	private

	def mark_stamp_as_purchased
	  if status == "Completed"
	    stamp.update_attribute(:description, 'Already Purchased')
	  end
	end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  before_action :set_payment_notification, only: [:create]
  protect_from_forgery :except => [:create]
  # GET /payment_notifications
  # GET /payment_notifications.json

  def create
    PaymentNotification.create(payment_notification_params)
    render :nothing => true
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_notification_params
      params.require(:payment_notification).permit(:params, :stamp_id, :status, :transaction_id, :create)
    end
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/views/payment_notifications/_form.html.erb
<%= simple_form_for(@payment_notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :params %>
    <%= f.input :stamp_id %>
    <%= f.input :status %>
    <%= f.input :transaction_id %>
    <%= f.input :create %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_notifications/edit.html.erb
<h1>Editing payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_notification %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/index.html.erb
<h1>Listing payment_notifications</h1>

<table>
  <thead>
    <tr>
      <th>Params</th>
      <th>Stamp</th>
      <th>Status</th>
      <th>Transaction</th>
      <th>Create</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_notifications.each do |payment_notification| %>
      <tr>
        <td><%= payment_notification.params %></td>
        <td><%= payment_notification.stamp_id %></td>
        <td><%= payment_notification.status %></td>
        <td><%= payment_notification.transaction_id %></td>
        <td><%= payment_notification.create %></td>
        <td><%= link_to 'Show', payment_notification %></td>
        <td><%= link_to 'Edit', edit_payment_notification_path(payment_notification) %></td>
        <td><%= link_to 'Destroy', payment_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment notification', new_payment_notification_path %>

app/views/payment_notifications/new.html.erb
<h1>New payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Params:</strong>
  <%= @payment_notification.params %>
</p>

<p>
  <strong>Stamp:</strong>
  <%= @payment_notification.stamp_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment_notification.status %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @payment_notification.transaction_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @payment_notification.create %>
</p>

<%= link_to 'Edit', edit_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', payment_notifications_path %>