config/routes.rb
StampApp::Application.routes.draw do
  resources :categories

  resources :payment_notifications
  	get 'tags/:tag', to: 'stamps#index', as: :tag
  
  resources :stamps do
    #get :clone
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
    
  resources :charges
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root :to => 'stamps#index'
  
  devise_for :admins
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'BanknoteStamps Home', "http://www.banknotestamps.com" %></li>
  <li><%= link_to 'All Stamps for Sale', root_path %></li>
  <li><%= link_to 'Contact Me', 'http://www.banknotestamps.com/Contact-Me' %></li>
  
  <% if admin_signed_in? -%>
    <li style="padding: 10px 15px 10px;">Signed in as <%= current_admin.email %></li>
  <% else %>
    <li><%= link_to 'Sign in as Admin', new_admin_session_path %></li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BanknoteStampShop" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learning Rails" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body style="background-color: #dddddd;" >
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
      	<div id="banner" >
				<img id="logo-img-id" width="180px" src="https://sites.google.com/site/banknotestamps/_/rsrc/1370536884723/config/customLogo.gif?revision=18" alt="Logo" class="sites-logo ">
     	</div>
        <div class="content">
            <div class="row">
           		<div class="span12"><h1>Stamps for Sale</h1><hr></div>       			
           	</div>
           	<div class="row">
            <div class="span3">
            	<h3>View by Category</h3>
            	<div id="tag_cloud">
            		<ul class="categories">
            		 <% @count = 0 %>
				 	 <% tag_cloud Stamp.tag_counts, %w[s m l] do |tag, css_class| %>
				    	<li><%= link_to tag.name + ' (' + Stamp.tag_counts[@count].count.to_s + ')', tag_path(tag.name), class: css_class %></li>
				    	<% @count = @count + 1%>
				  	 <% end %>
				  	 </ul>
				</div>
            </div>
            <div class="span9">	
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>